language: node_js
sudo: false
node_js:
- '6'
cache:
  yarn: true
  directories:
  - bower_components
branches:
  except:
  - "/^g3_.*$/"
env:
  matrix:
  - JOB=ci-checks
  - JOB=unit BROWSER_PROVIDER=saucelabs
  # - JOB=docs-e2e BROWSER_PROVIDER=saucelabs
  # - JOB=e2e TEST_TARGET=jqlite BROWSER_PROVIDER=saucelabs
  # - JOB=e2e TEST_TARGET=jquery BROWSER_PROVIDER=saucelabs
  global:
  - CXX=g++-4.8
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - LOGS_DIR=/tmp/angular-build/logs
  - BROWSER_PROVIDER_READY_FILE=/tmp/browsersprovider-tunnel-ready
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- du -sh ./node_modules ./bower_components/ || true
- "./scripts/travis/before_build.sh"
script: skip
# - "./scripts/travis/build.sh"
after_script:
- "./scripts/travis/tear_down_browser_provider.sh"
- "./scripts/travis/print_logs.sh"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d2120f3f2bb39a4531b2
    - http://104.197.9.155:8484/hubot/travis/activity
    on_success: always
    on_failure: always
    on_start: always
jobs:
  include:
    - stage: deploy
      script: grunt package && grunt compress:uploadBuild && echo $TRAVIS_BRANCH && echo $TRAVIS_TAG
      before_script: skip
      env:
        - JOB=deploy
      deploy:
        - provider: gcs
          access_key_id: GOOGLDB7W2J3LFHICF3R
          secret_access_key:
            secure: tHIFdSq55qkyZf9zT/3+VkhUrTvOTMuswxXU3KyWaBrSieZqG0UnUDyNm+n3lSfX95zEl/+rJAWbfvhVSxZi13ndOtvRF+MdI1cvow2JynP0aDSiPffEvVrZOmihD6mt2SlMfhskr5FTduQ69kZG6DfLcve1PPDaIwnbOv3phb8=
          bucket: ng-i-1121e.appspot.com
          local-dir: upload
          skip_cleanup: true
          detect_encoding: true # detects gzip compression and sets the correct metadata in gcs
          on:
            repo: angular/angular.js
            branch: chore-firebase
            # condition: $TRAVIS_TAG != false || ($TRAVIS_PR == false && $TRAVIS_BRANCH = master) || $TRAVIS_BRANCH = chore-firebase
        - provider: firebase
          skip_cleanup: true
          project: google.com:angular-sites
          token:
            secure: tHIFdSq55qkyZf9zT/3+VkhUrTvOTMuswxXU3KyWaBrSieZqG0UnUDyNm+n3lSfX95zEl/+rJAWbfvhVSxZi13ndOtvRF+MdI1cvow2JynP0aDSiPffEvVrZOmihD6mt2SlMfhskr5FTduQ69kZG6DfLcve1PPDaIwnbOv3phb8=
          on:
            repo: angular/angular.js
            # condition: $TRAVIS_BRANCH = chore-firebase
            branch: chore-firebase

